#!/usr/bin/env node

/**
 * campaign-import
 *
 * Reads a Campaign Map Builder export JSON and scaffolds (or updates) a
 * campaign inside a next-campaign-page-kit project:
 *
 *   _data/campaigns.json          — campaign registry entry
 *   src/{slug}/assets/config.js   — window.nextConfig (SDK init config)
 *   src/{slug}/*.html             — page stubs with frontmatter + routing
 *   src/{slug}/campaign-spec.json — copy of the source spec for reference
 *
 * Usage:
 *   campaign-import <path-to-export.json>
 */

const fs   = require('fs');
const path = require('path');
const config = require('../config');
const logger = require('../logger');

// Map builder page type + occurrence index → html filename
const TYPE_FILENAME = {
  presell:  'presale',
  landing:  'landing',
  checkout: 'checkout',
  upsell:   'upsell',
  downsell: 'downsell',
  thankyou: 'receipt',
};

// Map builder page type → Campaign Cart SDK page type (matches sdk_hints if present)
const SDK_PAGE_TYPE = {
  landing:  'product',
  presell:  'product',
  checkout: 'checkout',
  upsell:   'upsell',
  downsell: 'upsell',
  thankyou: 'receipt',
};

/**
 * Derive the html filename for a page, disambiguating duplicates by index.
 * e.g. first upsell → upsell.html, second → upsell-2.html
 */
function pageFilename(page, allPages) {
  const sameType = allPages.filter(p => p.type === page.type);
  const idx = sameType.findIndex(p => p.id === page.id);
  const base = TYPE_FILENAME[page.type] || page.type;
  const suffix = idx > 0 ? `-${idx + 1}` : '';
  return `${base}${suffix}.html`;
}

/** Resolve a page ID reference to its filename. Returns null if unresolved. */
function resolveRef(refId, pages, fileMap) {
  if (!refId) return null;
  const target = pages.find(p => p.id === refId);
  return target ? fileMap[target.id] : null;
}

/**
 * Generate window.nextConfig content from the export spec.
 * Maps available_shipping_countries and payment methods from the campaign
 * and global_config (sdk_version, gtm_container_id) into SDK init config.
 */
function generateConfigJs(spec) {
  const c  = spec.campaign      || {};
  const gc = spec.global_config || {};

  const countries       = c.available_shipping_countries      || [];
  const expressMethods  = (c.available_express_payment_methods || []).map(m => m.code || m).filter(Boolean);
  const defaultCountry  = countries[0] || 'US';
  const gtmEnabled      = !!(gc.gtm_container_id);
  const gtmId           = gc.gtm_container_id || '';

  // Build the config object — keep comments so the file is readable/editable
  const lines = [
    `// Generated by campaign-import from Campaign Map Builder`,
    `// Campaign: ${c.name || 'Unknown'} | Schema: ${spec.schema_version || '?'} | Built: ${spec.generated_at || new Date().toISOString()}`,
    `// Re-run campaign-import to regenerate from an updated spec.`,
    ``,
    `window.nextConfig = {`,
    `  apiKey: '${c.payment_env_key || ''}',`,
    `  debug: false,`,
    `  currencyBehavior: 'auto',`,
    ``,
    `  paymentConfig: {`,
    `    expressCheckout: {`,
    `      requireValidation: true,`,
    `      requiredFields: ['email', 'fname', 'lname'],`,
    expressMethods.length
      ? `      methodOrder: ${JSON.stringify(expressMethods)},`
      : `      methodOrder: ['paypal', 'apple_pay', 'google_pay'],`,
    `    }`,
    `  },`,
    ``,
    `  addressConfig: {`,
    `    defaultCountry: '${defaultCountry}',`,
    countries.length
      ? `    showCountries: ${JSON.stringify(countries)},`
      : `    showCountries: ['US'],`,
    `  },`,
    ``,
    `  tracking: 'auto',`,
    ``,
    `  analytics: {`,
    `    enabled: true,`,
    `    mode: 'auto',`,
    `    providers: {`,
    `      nextCampaign: { enabled: true },`,
    `      gtm: {`,
    `        enabled: ${gtmEnabled},`,
    `        settings: {`,
    `          containerId: '${gtmId}',`,
    `          dataLayerName: 'dataLayer',`,
    `        }`,
    `      },`,
    `      facebook: { enabled: false, settings: { pixelId: '' } },`,
    `    }`,
    `  },`,
    ``,
    `  utmTransfer: {`,
    `    enabled: true,`,
    `    applyToExternalLinks: false,`,
    `    debug: false,`,
    `  }`,
    `};`,
    ``,
  ];

  return lines.join('\n');
}

/**
 * Generate a page stub HTML file with YAML frontmatter.
 * Routing references are resolved from page IDs to filenames.
 */
function generatePageStub(page, fileMap, spec) {
  const pages  = spec.funnel_pages || [];
  const sdkType = (page.sdk_hints && page.sdk_hints.sdk_page_type) || SDK_PAGE_TYPE[page.type] || page.type;
  const filename = fileMap[page.id];

  // Build frontmatter fields
  const fm = {};
  fm['page_layout'] = 'base.html';
  fm['title']       = page.label;

  // template slug from builder selection
  if (page.template) fm['template'] = page.template;

  // routing — resolve page ID refs to filenames
  if (page.type === 'checkout' && page.success_url) {
    const target = resolveRef(page.success_url, pages, fileMap);
    if (target) fm['next_success_url'] = target;
  }
  if (page.type === 'upsell' || page.type === 'downsell') {
    const accept  = resolveRef(page.on_accept,  pages, fileMap);
    const decline = resolveRef(page.on_decline, pages, fileMap);
    if (accept)  fm['next_upsell_accept']  = accept;
    if (decline) fm['next_upsell_decline'] = decline;
    // First enabled upsell gets prevent-back-navigation per SDK hints
    if (page.sdk_hints?.meta_tags?.['next-prevent-back-navigation'] === 'true') {
      fm['next_prevent_back_navigation'] = 'true';
    }
  }
  if (page.type === 'presell' && page.next_page) {
    const target = resolveRef(page.next_page, pages, fileMap);
    if (target) fm['next_success_url'] = target;
  }

  // exit intent
  if (page.exit_intent?.enabled) {
    fm['exit_intent_enabled']  = true;
    if (page.exit_intent.offer_ref_id) fm['exit_intent_offer_ref_id'] = page.exit_intent.offer_ref_id;
    if (page.exit_intent.offer_code)   fm['exit_intent_offer_code']   = page.exit_intent.offer_code;
  }

  // internal notes as YAML comment placeholder
  const notesLine = page.notes ? `# Notes: ${page.notes}` : null;

  // Build YAML frontmatter string
  const yamlEntries = Object.entries(fm).map(([k, v]) => `${k}: ${v}`);

  const packagesSummary = (page.packages || []).map(p => {
    const name = p.name ? ` (${p.name})` : '';
    return `  # - ref_id: ${p.ref_id}${name} qty: ${p.qty}`;
  }).join('\n');

  const frontmatter = [
    '---',
    ...yamlEntries,
    ...(notesLine ? [notesLine] : []),
    '---',
  ].join('\n');

  const body = [
    `{%- comment -%}`,
    `  Page: ${page.label}`,
    `  Type: ${page.type}  |  SDK type: ${sdkType}`,
    `  Template: ${page.template || 'TBD — assign in Campaign Map Builder'}`,
    `  File: ${filename}`,
    `  Generated by campaign-import — edit frontmatter above, add content below.`,
    ...(packagesSummary ? [`  Packages:`, packagesSummary] : []),
    `{%- endcomment -%}`,
    ``,
    `{% comment %} TODO: Add page HTML content here {% endcomment %}`,
  ].join('\n');

  return `${frontmatter}\n${body}\n`;
}

// ──────────────────────────────────────────────────────────────────────────────

async function runImport(specPath) {
  const { intro, log, text, confirm, isCancel, outro } = await import('@clack/prompts');

  intro('Next Campaign Page Kit — campaign-import');

  // ── 1. Read & validate the spec ──────────────────────────────────────────
  if (!fs.existsSync(specPath)) {
    logger.error(`Spec file not found: ${specPath}`);
    process.exit(1);
  }

  let spec;
  try {
    spec = JSON.parse(fs.readFileSync(specPath, 'utf8'));
  } catch (e) {
    logger.error(`Failed to parse spec JSON: ${e.message}`);
    process.exit(1);
  }

  if (!spec.campaign || !spec.funnel_pages) {
    logger.error('Invalid spec: missing campaign or funnel_pages fields.');
    process.exit(1);
  }

  log.step(`Loaded spec: ${spec.campaign.name}  (schema v${spec.schema_version || '?'}, builder v${spec.builder_version || '?'})`);

  // ── 2. Confirm campaign slug ──────────────────────────────────────────────
  const defaultSlug = (spec.campaign.id || spec.campaign.name || 'campaign')
    .toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');

  const rawSlug = await text({
    message: 'Campaign slug (used as directory name and in URLs)',
    initialValue: defaultSlug,
    placeholder: defaultSlug,
    validate: v => !v.trim() ? 'Slug cannot be empty' : undefined,
  });
  if (isCancel(rawSlug)) process.exit(0);
  const slug = rawSlug.trim();

  // ── 3. Check for existing campaign ───────────────────────────────────────
  const srcPath      = config.getSrcPath();
  const campaignDir  = path.join(srcPath, slug);
  const specOutPath  = path.join(campaignDir, 'campaign-spec.json');

  let campaigns = [];
  try { campaigns = config.loadCampaigns(); } catch (_) { /* campaigns.json may not exist yet */ }

  const existingIdx = campaigns.findIndex(c => c.slug === slug);
  if (existingIdx >= 0) {
    const ok = await confirm({
      message: `Campaign "${slug}" already exists. Overwrite config.js and page stubs?`,
      initialValue: false,
    });
    if (isCancel(ok) || !ok) {
      log.warn('Import cancelled.');
      process.exit(0);
    }
  }

  // ── 4. Build page → filename map ─────────────────────────────────────────
  const pages   = spec.funnel_pages || [];
  const fileMap = {};
  pages.forEach(p => { fileMap[p.id] = pageFilename(p, pages); });

  log.step(`Mapping ${pages.length} pages: ${pages.map(p => `${fileMap[p.id]} (${p.type})`).join(', ')}`);

  // ── 5. Update _data/campaigns.json ───────────────────────────────────────
  const gc = spec.global_config || {};
  const campaignEntry = {
    name:            spec.campaign.name,
    slug,
    description:     `Imported from Campaign Map Builder — ${new Date().toLocaleDateString()}`,
    sdk_version:     gc.sdk_version || '0.3.7',
    ...(spec.campaign.payment_env_key ? { payment_env_key: spec.campaign.payment_env_key } : {}),
    ...(spec.figma_url ? { figma_url: spec.figma_url } : {}),
  };

  if (existingIdx >= 0) {
    campaigns[existingIdx] = { ...campaigns[existingIdx], ...campaignEntry };
  } else {
    campaigns.push(campaignEntry);
  }

  // Ensure _data dir exists
  const dataDir = path.join(config.getProjectRoot(), '_data');
  fs.mkdirSync(dataDir, { recursive: true });
  config.saveCampaigns(campaigns);
  log.success('Updated _data/campaigns.json');

  // ── 6. Create campaign directory structure ───────────────────────────────
  fs.mkdirSync(path.join(campaignDir, 'assets', 'css'),    { recursive: true });
  fs.mkdirSync(path.join(campaignDir, 'assets', 'js'),     { recursive: true });
  fs.mkdirSync(path.join(campaignDir, 'assets', 'images'), { recursive: true });
  fs.mkdirSync(path.join(campaignDir, '_layouts'),         { recursive: true });
  fs.mkdirSync(path.join(campaignDir, '_includes'),        { recursive: true });

  // ── 7. Generate assets/config.js ─────────────────────────────────────────
  const configJs = generateConfigJs(spec);
  fs.writeFileSync(path.join(campaignDir, 'assets', 'config.js'), configJs, 'utf8');
  log.success('Generated assets/config.js');

  // ── 8. Generate page stubs ────────────────────────────────────────────────
  pages.forEach(page => {
    const filename = fileMap[page.id];
    const html     = generatePageStub(page, fileMap, spec);
    fs.writeFileSync(path.join(campaignDir, filename), html, 'utf8');
    log.step(`  → ${filename}  (${page.type}${page.template ? ` · ${page.template}` : ''})`);
  });
  log.success(`Generated ${pages.length} page stubs`);

  // ── 9. Save spec for reference ────────────────────────────────────────────
  fs.writeFileSync(specOutPath, JSON.stringify(spec, null, 2), 'utf8');
  log.success('Saved campaign-spec.json');

  // ── 10. Summary ───────────────────────────────────────────────────────────
  outro(
    `Import complete!\n` +
    `  Campaign:  ${spec.campaign.name}\n` +
    `  Slug:      ${slug}\n` +
    `  Directory: src/${slug}/\n` +
    `  SDK:       campaign-cart@v${gc.sdk_version || '0.3.7'}\n` +
    `  Pages:     ${pages.map(p => fileMap[p.id]).join(', ')}\n\n` +
    `Next steps:\n` +
    `  1. Add base.html layout to src/${slug}/_layouts/\n` +
    `  2. Add design assets to src/${slug}/assets/\n` +
    `  3. Run npm run dev to preview`
  );
}

// ──────────────────────────────────────────────────────────────────────────────

async function main() {
  const specPath = process.argv[2];
  if (!specPath) {
    console.error('Usage: campaign-import <path-to-export.json>');
    console.error('       Export a spec from campaign-map.nextcommerce.com then pass the file here.');
    process.exit(1);
  }
  await runImport(path.resolve(specPath));
}

if (require.main === module) {
  main().catch(err => {
    logger.error(err.message);
    process.exit(1);
  });
}

module.exports = { runImport };
